/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdvisoryRouteImport } from './routes/advisory'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EuAiActRouteImport } from './routes/eu-ai-act'
import { Route as FounderRouteImport } from './routes/founder'
import { Route as ImeRouteImport } from './routes/ime'
import { Route as LiveTrainerRouteImport } from './routes/live-trainer'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PrivateAiRouteImport } from './routes/private-ai'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as TeamTrainingRouteImport } from './routes/team-training'
import { Route as ImeExecutiveRouteImport } from './routes/ime.executive'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisoryRoute = AdvisoryRouteImport.update({
  id: '/advisory',
  path: '/advisory',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EuAiActRoute = EuAiActRouteImport.update({
  id: '/eu-ai-act',
  path: '/eu-ai-act',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderRoute = FounderRouteImport.update({
  id: '/founder',
  path: '/founder',
  getParentRoute: () => rootRouteImport,
} as any)
const ImeRoute = ImeRouteImport.update({
  id: '/ime',
  path: '/ime',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveTrainerRoute = LiveTrainerRouteImport.update({
  id: '/live-trainer',
  path: '/live-trainer',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateAiRoute = PrivateAiRouteImport.update({
  id: '/private-ai',
  path: '/private-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamTrainingRoute = TeamTrainingRouteImport.update({
  id: '/team-training',
  path: '/team-training',
  getParentRoute: () => rootRouteImport,
} as any)
const ImeExecutiveRoute = ImeExecutiveRouteImport.update({
  id: '/executive',
  path: '/executive',
  getParentRoute: () => ImeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advisory': typeof AdvisoryRoute
  '/contact': typeof ContactRoute
  '/eu-ai-act': typeof EuAiActRoute
  '/founder': typeof FounderRoute
  '/ime': typeof ImeRouteWithChildren
  '/live-trainer': typeof LiveTrainerRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/private-ai': typeof PrivateAiRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio': typeof StudioRoute
  '/team-training': typeof TeamTrainingRoute
  '/ime/executive': typeof ImeExecutiveRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advisory': typeof AdvisoryRoute
  '/contact': typeof ContactRoute
  '/eu-ai-act': typeof EuAiActRoute
  '/founder': typeof FounderRoute
  '/ime': typeof ImeRouteWithChildren
  '/live-trainer': typeof LiveTrainerRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/private-ai': typeof PrivateAiRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio': typeof StudioRoute
  '/team-training': typeof TeamTrainingRoute
  '/ime/executive': typeof ImeExecutiveRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advisory': typeof AdvisoryRoute
  '/contact': typeof ContactRoute
  '/eu-ai-act': typeof EuAiActRoute
  '/founder': typeof FounderRoute
  '/ime': typeof ImeRouteWithChildren
  '/live-trainer': typeof LiveTrainerRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/private-ai': typeof PrivateAiRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio': typeof StudioRoute
  '/team-training': typeof TeamTrainingRoute
  '/ime/executive': typeof ImeExecutiveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/advisory'
    | '/contact'
    | '/eu-ai-act'
    | '/founder'
    | '/ime'
    | '/live-trainer'
    | '/onboarding'
    | '/privacy'
    | '/private-ai'
    | '/sitemap.xml'
    | '/studio'
    | '/team-training'
    | '/ime/executive'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/advisory'
    | '/contact'
    | '/eu-ai-act'
    | '/founder'
    | '/ime'
    | '/live-trainer'
    | '/onboarding'
    | '/privacy'
    | '/private-ai'
    | '/sitemap.xml'
    | '/studio'
    | '/team-training'
    | '/ime/executive'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/advisory'
    | '/contact'
    | '/eu-ai-act'
    | '/founder'
    | '/ime'
    | '/live-trainer'
    | '/onboarding'
    | '/privacy'
    | '/private-ai'
    | '/sitemap.xml'
    | '/studio'
    | '/team-training'
    | '/ime/executive'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdvisoryRoute: typeof AdvisoryRoute
  ContactRoute: typeof ContactRoute
  EuAiActRoute: typeof EuAiActRoute
  FounderRoute: typeof FounderRoute
  ImeRoute: typeof ImeRouteWithChildren
  LiveTrainerRoute: typeof LiveTrainerRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  PrivateAiRoute: typeof PrivateAiRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StudioRoute: typeof StudioRoute
  TeamTrainingRoute: typeof TeamTrainingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisory': {
      id: '/advisory'
      path: '/advisory'
      fullPath: '/advisory'
      preLoaderRoute: typeof AdvisoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eu-ai-act': {
      id: '/eu-ai-act'
      path: '/eu-ai-act'
      fullPath: '/eu-ai-act'
      preLoaderRoute: typeof EuAiActRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder': {
      id: '/founder'
      path: '/founder'
      fullPath: '/founder'
      preLoaderRoute: typeof FounderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ime': {
      id: '/ime'
      path: '/ime'
      fullPath: '/ime'
      preLoaderRoute: typeof ImeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-trainer': {
      id: '/live-trainer'
      path: '/live-trainer'
      fullPath: '/live-trainer'
      preLoaderRoute: typeof LiveTrainerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/private-ai': {
      id: '/private-ai'
      path: '/private-ai'
      fullPath: '/private-ai'
      preLoaderRoute: typeof PrivateAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team-training': {
      id: '/team-training'
      path: '/team-training'
      fullPath: '/team-training'
      preLoaderRoute: typeof TeamTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ime/executive': {
      id: '/ime/executive'
      path: '/executive'
      fullPath: '/ime/executive'
      preLoaderRoute: typeof ImeExecutiveRouteImport
      parentRoute: typeof ImeRoute
    }
  }
}

interface ImeRouteChildren {
  ImeExecutiveRoute: typeof ImeExecutiveRoute
}

const ImeRouteChildren: ImeRouteChildren = {
  ImeExecutiveRoute: ImeExecutiveRoute,
}

const ImeRouteWithChildren = ImeRoute._addFileChildren(ImeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdvisoryRoute: AdvisoryRoute,
  ContactRoute: ContactRoute,
  EuAiActRoute: EuAiActRoute,
  FounderRoute: FounderRoute,
  ImeRoute: ImeRouteWithChildren,
  LiveTrainerRoute: LiveTrainerRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  PrivateAiRoute: PrivateAiRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StudioRoute: StudioRoute,
  TeamTrainingRoute: TeamTrainingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
